Class {
	#name : #CampingSiteDataModelV2,
	#superclass : #Object,
	#instVars : [
		'description',
		'coordinates',
		'id'
	],
	#category : #CampingWebApp
}

{ #category : #accessing }
CampingSiteDataModelV2 >> coordinates [

	^ coordinates
]

{ #category : #accessing }
CampingSiteDataModelV2 >> coordinates: anObject [

	coordinates := anObject
]

{ #category : #accessing }
CampingSiteDataModelV2 >> description [

	^ description
]

{ #category : #accessing }
CampingSiteDataModelV2 >> description: anObject [

	description := anObject
]

{ #category : #accessing }
CampingSiteDataModelV2 >> id [

	^ id
]

{ #category : #accessing }
CampingSiteDataModelV2 >> id: anObject [

	id := anObject
]
