Class {
	#name : #CampingSiteDataModelV1,
	#superclass : #Object,
	#instVars : [
		'name',
		'description',
		'coordinates',
		'id'
	],
	#category : #CampingWebApp
}

{ #category : #accessing }
CampingSiteDataModelV1 >> coordinates [

	^ coordinates
]

{ #category : #accessing }
CampingSiteDataModelV1 >> coordinates: anObject [

	coordinates := anObject
]

{ #category : #accessing }
CampingSiteDataModelV1 >> description [

	^ description
]

{ #category : #accessing }
CampingSiteDataModelV1 >> description: anObject [

	description := anObject
]

{ #category : #accessing }
CampingSiteDataModelV1 >> id [

	^ id
]

{ #category : #accessing }
CampingSiteDataModelV1 >> id: anObject [

	id := anObject
]

{ #category : #accessing }
CampingSiteDataModelV1 >> name [

	^ name
]

{ #category : #accessing }
CampingSiteDataModelV1 >> name: anObject [

	name := anObject
]
